### PR TITLE
Changes UriString to be stored as json list.

### PR DESCRIPTION
**Pull request by brialee**

### CODE REVIEW

**Review by Jbrusaw — COMMENTED** [review]
I'm getting this error when running it. I'm thinking it's because the existing data in my database is in the CSV format but your setter is expecting the JSON format, right?

If so, then we need to write some script that can go through an existing DB and convert everything to the correct format before deploying this to the demo server so we don't have to delete all the data in the DB

image

**Review by ohyonghao — CHANGES_REQUESTED** [review]
Code looks great, the one thing missing is a migration from the old format to the new.

**Comment by unstable-compound** [comment]
> 
> 
> I'm getting this error when running it. I'm thinking it's because the existing data in my database is in the CSV format but your setter is expecting the JSON format, right?
> 
> If so, then we need to write some script that can go through an existing DB and convert everything to the correct format before deploying this to the demo server so we don't have to delete all the data in the DB
> 
> image

On this note, changes that affect the way we interact with DB needs to backwards compatable with the live beta!

**Comment by unstable-compound** [comment]
What is the status on this PR? It appears to have been inactive for quite some time

**Comment by Jbrusaw** [comment]
I believe we're waiting on Brian to implement backwards-compatibility

**Comment by ohyonghao** [comment]
Closing pull request until changes are added.

**Pull request closed without merging**
